// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudYHUKJ8loxmHPiP9j6TrPwknqc18DWE',
    appId: '1:828865002983:web:6dca0419dd526b008b9142',
    messagingSenderId: '828865002983',
    projectId: 'virtuchat',
    authDomain: 'virtuchat.firebaseapp.com',
    storageBucket: 'virtuchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1edCWNUMQlWJLYgkO3jzhGWWDEE79fcc',
    appId: '1:828865002983:android:de04cc073f4ff4da8b9142',
    messagingSenderId: '828865002983',
    projectId: 'virtuchat',
    storageBucket: 'virtuchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1cT-sq-eB4Y10cCVlv-22uA7QGvnCu8',
    appId: '1:828865002983:ios:78a60463ee5bb5e28b9142',
    messagingSenderId: '828865002983',
    projectId: 'virtuchat',
    storageBucket: 'virtuchat.appspot.com',
    iosBundleId: 'com.example.virtuchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1cT-sq-eB4Y10cCVlv-22uA7QGvnCu8',
    appId: '1:828865002983:ios:bf1499921d17ac0c8b9142',
    messagingSenderId: '828865002983',
    projectId: 'virtuchat',
    storageBucket: 'virtuchat.appspot.com',
    iosBundleId: 'com.example.virtuchat.RunnerTests',
  );
}
